name: cxx11

on:
  push:
    branches: [ v1.5.3.qeep ]
  pull_request:
    branches: [ v1.5.3.qeep ]
  workflow_dispatch:
    inputs:
      qispace_sdk_ver:
        description: qispace sdk version, eg R1.9.0
        type: string
        required: true

jobs:
  build:
    name: ubuntu
    runs-on: ubuntu-20.04
    env:
      QISPACE_SDK_VER: "${{ inputs.qispace_sdk_ver || 'R1.9.0' }}"

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ORG_S3_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ORG_S3_AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Download QiSpace SDK
      run: |
        mkdir -p qispace_qeep
        aws s3 cp s3://qispace-sdk-release/${{ env.QISPACE_SDK_VER }}/qispace-QEEP-SDK-${{ env.QISPACE_SDK_VER }}-ubuntu.zip qispace_qeep/qispace-QEEP-SDK-${{ env.QISPACE_SDK_VER }}-ubuntu.zip
        unzip qispace_qeep/qispace-QEEP-SDK-${{ env.QISPACE_SDK_VER }}-ubuntu.zip -d qispace_qeep

    - name: configure
      run: |
        mkdir _build && cd _build
        cmake ../ -DENABLE_STDCXX_SYNC=ON -DUSE_ENCLIB=qispace -DENABLE_TESTING=ON -DENABLE_EXAMPLES=ON -DQISPACE_SDK_DIR="../qispace_qeep"
    - name: build
      run: cd _build && cmake --build ./
    - name: test
      run: cd _build && ctest --extra-verbose

    - name: Archive build results
      uses: actions/upload-artifact@v4
      with:
        name: qsrt-qeep
        path: |
          _build
        retention-days: 1